
name: Sync Issues to Central Dashboard

on:
  issues:
    types: [opened, edited]

jobs:
  sync_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Sync issue to central repository
      uses: peter-evans/create-issue-from-file@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: neryguzman/central-dashboard
        title: ${{ github.event.issue.title }}
        content-filepath: ""  # Remove invalid content field
        labels: >
          company:NeryAly
          repository:MarketingStrategyJPN
          status:${{ github.event.issue.state }}
          assignee:${{ github.event.issue.assignee.login }}
